Vagrant.configure("2") do |config|
  config.vm.define "nodo1" do |nodo1|
    nodo1.vm.box = "ubuntu/bionic64"
    nodo1.vm.hostname = "nodo1"
    nodo1.vm.network "private_network", ip: "192.168.56.11"
    nodo1.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y docker.io
      systemctl enable docker
      usermod -aG docker vagrant
    SHELL
  end

  config.vm.define "nodo2" do |nodo2|
    nodo2.vm.box = "ubuntu/bionic64"
    nodo2.vm.hostname = "nodo2"
    nodo2.vm.network "private_network", ip: "192.168.56.12"
    nodo2.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y docker.io
      systemctl enable docker
      usermod -aG docker vagrant
    SHELL
  end
end
